name: worditkid
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_player_flutter: ^7.0.0+7
  firebase_database: ^3.1.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_tts: ^0.6.0
  audioplayers: 0.11.0
  flip_card: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.16.1
  provider: ^4.3.1
  simple_animations: ^1.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - Images/Redirection/background.png
    - Images/Redirection/frog.png
    - Images/Redirection/girrafe.png
    - Images/Redirection/bird.png
    - Images/Redirection/singSymbol.png
    - Images/Redirection/gamesSymbol.png
    - Images/Redirection/LearnSymbol.png
    - Images/Home/HomeBG.png
    - Images/Home/Heading.png
    - Images/Games/gtc.png
    - Images/Games/ttt.png
    - Images/Games/GameBG.png
    - Images/Games/memory-game.png
    - Images/Rhymes/RhymesBG.png
    - Images/seasons/action.png
    - Images/seasons/alphanary.png
    - Images/seasons/autumn-bg.png
    - Images/seasons/describe.png
    - Images/seasons/form.png
    - Images/seasons/naming.png
    - Images/seasons/rhyme.png
    - Images/seasons/summer-bg.png
    - Images/seasons/winter-bg.png
    - Images/seasons/rain-bg.png
    - Images/seasons/opp.png
    - Images/seasons/opp-bg.png
    - Images/seasons/pink-bg.png
    - Images/seasons/pink.png
    - Images/seasons/similar.png
    - Images/seasons/singular.png
    - Images/seasons/sing-full.png
    - Images/seasons/naming-full.png
    - Images/seasons/describe-full.png
    - Images/seasons/action-full.png
    - Images/seasons/intro-full.png
    - Images/Opposite/closed.png
    - Images/Opposite/dark.png
    - Images/Opposite/empty.png
    - Images/Opposite/fast.png
    - Images/Opposite/full.png
    - Images/Opposite/happy.png
    - Images/Opposite/light.png
    - Images/Opposite/old.png
    - Images/Opposite/open.png
    - Images/Opposite/sad.png
    - Images/Opposite/slow.png
    - Images/Opposite/young.png
    - Images/similar/big.png
    - Images/similar/fast.png
    - Images/similar/grin.png
    - Images/similar/large.png
    - Images/similar/sad.png
    - Images/similar/small.png
    - Images/similar/smile.png
    - Images/similar/speedy.png
    - Images/similar/tiny.png
    - Images/similar/unhappy.png
    - Images/NamingWords/name_f.png
    - Images/NamingWords/name_b.png
    - Images/NamingWords/place_f.png
    - Images/NamingWords/place_b.png
    - Images/NamingWords/thing_f.png
    - Images/NamingWords/thing_b.png
    - Images/NamingWords/boy_f.png
    - Images/NamingWords/boy_b.png
    - Images/DescribingWords/big.png
    - Images/DescribingWords/pink.png
    - Images/DescribingWords/sweet.png
    - Images/DescribingWords/tasty.png
    - Images/Action/run.gif
    - Images/Action/run.png
    - Images/Action/eat.gif
    - Images/Action/eat.png
    - Images/Action/jump.png
    - Images/Action/jump.gif
    - Images/Action/drive.gif
    - Images/Action/drive.png
    - Images/sp/ant.png
    - Images/sp/ants.png
    - Images/sp/apple.png
    - Images/sp/apples.png
    - Images/sp/box.png
    - Images/sp/boxes.png
    - Images/sp/cat.png
    - Images/sp/cats.png
    - Images/sp/hat.png
    - Images/sp/hats.png
    - 'success.mp3'
    - Images/apple.png
    - Images/banana.png
    - Images/cat.png
    - Images/dog.png
    - Images/elephant.png
    - Images/fish.png
    - Images/grapes.png
    - Images/hen.png
    - Images/Jug.png
    - Images/kite.png
    - Images/lion.png
    - Images/mango.png
    - Images/nest.png
    - Images/IceCream.png
    - Images/sun.png
    - Images/queen.png
    - Images/owl.png
    - Images/peacock.png
    - Images/rose.png
    - Images/zebra.png
    - Images/Van.png
    - Images/telephone.png
    - Images/yak.png
    - Images/xylophone.png
    - Images/watch.png
    - Images/Umbrella.png
    - Images/ant.png
    - Images/arrow.png
    - Images/axe.png
    - Images/bat.png
    - Images/ball.png
    - Images/cup.png
    - Images/Camel.png
    - Images/car.png
    - Images/Bee.png
    - Images/egg.png
    - Images/fire.png
    - Images/fairy.png
    - Images/desk.png
    - Images/Engine.png
    - Images/duck.png
    - Images/eagle.png
    - Images/Donkey.png
    - Images/gold.png
    - Images/Guava.png
    - Images/goat.png
    - Images/Hat.png
    - Images/Horse.png
    - Images/hut.png
    - Images/igloo.png
    - Images/Injection.png
    - Images/inkpot.png
    - Images/Jackal.png
    - Images/joker.png
    - Images/Jungle.png
    - Images/Kangaroo.png
    - Images/kettle.png
    - Images/king.png
    - Images/mat.png
    - Images/monkey.png
    - Images/mouse.png
    - Images/leopeard.png
    - Images/lemon.png
    - Images/lamp.png
    - Images/ox.png
    - Images/orange.png
    - Images/Quote.png
    - Images/quill.png
    - Images/oven.png
    - Images/quiet.png
    - Images/pen.png
    - Images/Nip.png
    - Images/net.png
    - Images/potato.png
    - Images/nose.png
    - Images/pencil.png
    - Images/rack.png
    - Images/uncle.png
    - Images/toy.png
    - Images/sing.png
    - Images/urban.png
    - Images/snake.png
    - Images/rat.png
    - Images/ring.png
    - Images/train.png
    - Images/star.png
    - Images/tea.png
    - Images/urn.png
    - Images/Voilet.png
    - Images/vest.png
    - Images/violin.png
    - Images/wall.png
    - Images/wallet.png
    - Images/wallnut.png
    - Images/yoga.png
    - Images/yatch.png
    - Images/yo - yo.png
    - Images/Zero.png
    - Images/zip.png
    - Images/zoo.png
    - Images/x -ray.png
    - Images/X-mas tree.png
    - Images/X-ray.jpg
    - Images/Forest.png
    - Images/girrafe.png
    - Images/RhymingWords/call.png
    - Images/RhymingWords/tall.png
    - Images/RhymingWords/jar.png
    - Images/RhymingWords/war.png
    - Images/RhymingWords/bar.png
    - Images/RhymingWords/pot.png
    - Images/RhymingWords/dot.png
    - Images/RhymingWords/cot.png
    - Images/RhymingWords/can.png
    - Images/RhymingWords/pan.png
    - Images/RhymingWords/grass.png
    - Images/RhymingWords/hot.png
    - Images/Levels/LearnBG.png
    - Images/Levels/alphanary.png
    - Images/Levels/rhyming_words.png
    - Images/Levels/form_words.png
    - Images/Levels/intro.png
    - Images/seasons/summer-bg.png
    - Images/tick.png
    - Images/Games/XorO_2.png
    - Images/Games/MatchColor.png
    - Images/Games/Leaves.jpg
    - Images/seasons/vowels.png
    - Images/vowels/vowels-heading.png
    - Images/vowels/vowels-box.png
    - Images/ExerciseImages/treasure.png
    - Images/ExerciseImages/coin.png
    - Images/ExerciseImages/crown.gif
    - Images/seasons/autumn-bg.png
    - 'Sound/Miracle-sound-effect.mp3'
    - Images/ExerciseImages/blocks.png
    - Images/ExerciseImages/donut.png
    - Images/ExerciseImages/teddyBear.png
    - Images/ExerciseImages/giftBox.png
    - Images/ExerciseImages/ball.png
    - Images/jungle4.png
    - assets/
    - Images/Games/snake-game.png
    - Images/ExerciseKGImages/carrot.png
    - Images/ExerciseKGImages/Gloves.png
    - Images/ExerciseKGImages/Hat.png
    - Images/ExerciseKGImages/IceBlock.png
    - Images/ExerciseKGImages/scarf.png
    - Images/ExerciseKGImages/Branches.png
    - Images/ExerciseKGImages/Snowman.gif
    - Images/seasons/KennelView.png
    - Images/ExerciseKGImages/path.png
    - Images/ExerciseKGImages/Kennel.png
    - Images/ExerciseKGImages/AngryPenguin.gif
    - Images/ExerciseKGImages/dog2.gif
    - Images/ExerciseKGImages/Elephant.gif
    - Images/ExerciseKGImages/girrafe.gif
    - Images/ExerciseKGImages/HappyPanda.gif




  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
