name: worditkid
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_player_flutter: ^7.0.0+7


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  audioplayers: 0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - Images/background.png
    - Images/frog.png
    - Images/girrafe.png
    - Images/bird.png
    - Images/singSymbol.png
    - Images/gamesSymbol.png
    - Images/LearnSymbol.png
    - Images/HomeBG.png
    - Images/Heading.png
    - Images/gtc.png
    - Images/GameBG.png
    - Images/RhymesBG.png
    - 'success.mp3'
    - Images/apple.png
    - Images/banana.png
    - Images/cat.png
    - Images/dog.png
    - Sounds/a (1).mp3
    - Images/elephant.png
    - Images/fish.png
    - Images/grapes.png
    - Images/hen.png
    - Images/Jug.png
    - Images/kite.png
    - Images/lion.png
    - Images/mango.png
    - Images/nest.png
    - Images/IceCream.png
    - Images/sun.png
    - Images/queen.png
    - Images/owl.png
    - Images/peacock.png
    - Images/rose.png
    - Images/zebra.png
    - Images/Van.png
    - Images/telephone.png
    - Images/yak.png
    - Images/xylophone.png
    - Images/watch.png
    - Images/Umbrella.png
    - Images/ant.png
    - Images/arrow.png
    - Images/axe.png
    - Images/bat.png
    - Images/ball.png
    - Images/cup.png
    - Images/Camel.png
    - Images/car.png
    - Images/Bee.png
    - Images/egg.png
    - Images/fire.png
    - Images/fairy.png
    - Images/desk.png
    - Images/Engine.png
    - Images/duck.png
    - Images/eagle.png
    - Images/Donkey.png
    - Images/gold.png
    - Images/Guava.png
    - Images/goat.png
    - Images/Hat.png
    - Images/Horse.png
    - Images/hut.png
    - Images/igloo.png
    - Images/Injection.png
    - Images/inkpot.png
    - Images/Jackal.png
    - Images/joker.png
    - Images/Jungle.png
    - Images/Kangaroo.png
    - Images/kettle.png
    - Images/king.png
    - Images/mat.png
    - Images/monkey.png
    - Images/mouse.png
    - Images/leopeard.png
    - Images/lemon.png
    - Images/lamp.png
    - Images/ox.png
    - Images/orange.png
    - Images/Quote.png
    - Images/quill.png
    - Images/oven.png
    - Images/quiet.png
    - Images/pen.png
    - Images/Nip.png
    - Images/net.png
    - Images/potato.png
    - Images/nose.png
    - Images/pencil.png
    - Images/rack.png
    - Images/uncle.png
    - Images/toy.png
    - Images/sing.png
    - Images/urban.png
    - Images/snake.png
    - Images/rat.png
    - Images/ring.png
    - Images/train.png
    - Images/star.png
    - Images/tea.png
    - Images/urn.png
    - Images/Voilet.png
    - Images/vest.png
    - Images/violin.png
    - Images/wall.png
    - Images/wallet.png
    - Images/wallnut.png
    - Images/yoga.png
    - Images/yatch.png
    - Images/yo - yo.png
    - Images/Zero.png
    - Images/zip.png
    - Images/zoo.png
    - Images/x -ray.png
    - Images/X-mas tree.png
    - Images/X-ray.jpg
    - Images/Forest.png




  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PressStart
      fonts:
        - asset: assets/PressStart2P-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
